# Generated by Django 4.2.2 on 2023-06-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(verbose_name='birth_date')),
            ],
            options={
                'verbose_name': 'Актёр',
                'verbose_name_plural': 'Актёры',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Комедия', 'Comedy'), ('Хоррор', 'Horror'), ('Драма', 'Drama'), ('Триллер', 'Thriller'), ('Боевик', 'Action'), ('Документальный', 'Documentary'), ('История', 'Story')], max_length=24, verbose_name='genre')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('directors', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('release', models.DateField()),
                ('actors', models.ManyToManyField(related_name='movies', to='movies.actor')),
                ('genre', models.ManyToManyField(to='movies.genres')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.AddField(
            model_name='genres',
            name='movies',
            field=models.ManyToManyField(blank=True, to='movies.movie'),
        ),
    ]
